Added paragraph to explain what's included in a Self-Description
International-Data-Spaces-Association/IDS-RAM_4_0 pull request #216
Opened 2022-11-11 13:10 UTC by tom-rm-meyer-ISST

- Self-Description of the component
- Self-Description of the offered endpoints
- Self-Description of the offered data

2022-11-11 13:11 UTC, tom-rm-meyer-ISST commented
Proposal to solve https://github.com/International-Data-Spaces-Association/IDS-RAM_4_0/issues/213

2022-11-11 14:17 UTC, sebbader-sap commented on documentation/3_Layers_of_the_Reference_Architecture_Model/3_5_System_Layer/3_5_4_Metadata_Broker.md
> +The IDS Metadata Broker consists of an IDS Connector (see Section [3.5.2](./3_5_2_IDS_Connector.md#ids-connector)), an endpoint for the registration, publication, maintenance, and query of Self-Descr
I would rather say that "The IDS Metadata Broker is an IDS Connector (see Section [3.5.2](./3_5_2_IDS_Connector.md#ids-connector)), which contains an endpoint for the registration ..."

2022-11-11 14:18 UTC, sebbader-sap commented on documentation/3_Layers_of_the_Reference_Architecture_Model/3_5_System_Layer/3_5_4_Metadata_Broker.md
> +A Self-Description encapsulates information about the component hosted within an IDS Connector. This Self-Description contains information about the offered interfaces, the owner of the component and
A Self-Description encapsulates information about the IDS Connector itself and its capabilities and characteristics. ... A Self-Description is provided by the operator of the Connector. ...

2022-11-11 14:22 UTC, sebbader-sap commented on documentation/3_Layers_of_the_Reference_Architecture_Model/3_5_System_Layer/3_5_4_Metadata_Broker.md
> +An IDS Connector providing a service or data can send its Self-Description to a IDS Metadata Broker so that every participant is able to find it within the dataspace. The IDS Metadata Broker can be u
... Within a dataspace, there can be multiple IDS Metadata Brokers allowing to distribute the IDS Metadata Broker functionality. It is up to the dataspace authority to decide if there is a leading IDS Metadata Broker or if the different instances operate independently.

2022-11-11 14:22 UTC, sebbader-sap commented on documentation/3_Layers_of_the_Reference_Architecture_Model/3_5_System_Layer/3_5_4_Metadata_Broker.md
> +A participant can interact with an IDS Metadata Broker by using the processes defined on the Process Layer, the descriptions defined on the Information Layer, and descriptions defined on the System L
... The Information Layer describes the message types for registration and query as well as their content. ...

2022-11-11 15:34 UTC, sebbader approved these changes

2023-01-25 08:31 UTC, ssteinbuss commented on documentation/3_Layers_of_the_Reference_Architecture_Model/3_5_System_Layer/3_5_4_Metadata_Broker.md
> +A Self-Description encapsulates information about IDS Connector itself and its capabilities and characteristics. This Self-Description contains information about the offered interfaces, the owner of
Typo in Connector, please avoid mixing HTML tags with the text. use an empty line instead

2023-01-25 08:33 UTC, ssteinbuss requested changes
Thanks a lot for contributing here. Contentwise great input, please check again for typos and remove HTML tags mixed with the text.

2023-01-25 08:35 UTC, ssteinbuss approved these changes

2023-02-15 01:40 UTC, merged